

GET http://localhost:8080/api/tasks
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6ImVkNmJjOWRhMWFmMjM2ZjhlYTU2YTVkNjIyMzQwMWZmNGUwODdmMTEiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vbmV4dGpzdHV0b3JpYWwtYzM0ODIiLCJhdWQiOiJuZXh0anN0dXRvcmlhbC1jMzQ4MiIsImF1dGhfdGltZSI6MTY2MjcwOTgzMCwidXNlcl9pZCI6ImZQcHdqTlQ3UVZkZWg3ZzdDSFFwSlljTlBpczIiLCJzdWIiOiJmUHB3ak5UN1FWZGVoN2c3Q0hRcEpZY05QaXMyIiwiaWF0IjoxNjYyNzA5ODMwLCJleHAiOjE2NjI3MTM0MzAsInBob25lX251bWJlciI6Iis5MTk5ODA4NjkyNjYiLCJmaXJlYmFzZSI6eyJpZGVudGl0aWVzIjp7InBob25lIjpbIis5MTk5ODA4NjkyNjYiXX0sInNpZ25faW5fcHJvdmlkZXIiOiJwaG9uZSJ9fQ.cqRL0V77KOFR8Qdh1Z0RleGXIbfgKgpF0nOjR4798R_9OZHo1FARBMp5tLNTJNpgjhl6KLjSps2v0zGO2PzATJ-4tkMKphaqMB7sUbprYoxTRm3VcKZJt-khsgj3ZUMVW-YKKI17daq9xsPnilQAgqRFWjeCxDIfrB2qr_xMmF-mB_M_aH98_H364AmcKsDnpo71BB0W957eQFD7GgOELoiuZlCQGpo77swagVaMd8xgElk63x2cJ7mIpvmDnViIyqh7m-3mdKGCiPBmK2uTr-upyuMbbCel0nGgZHRNd6CdytWKYJXKYN1ETCPekyVcjR2hkgUU81oT1NPDI4D2ag